/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as DespensaRouteImport } from './routes/despensa'
import { Route as DicasRouteImport } from './routes/dicas'
import { Route as ReceitaIdRouteImport } from './routes/receita.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DespensaRoute = DespensaRouteImport.update({
  id: '/despensa',
  path: '/despensa',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasRoute = DicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaIdRoute = ReceitaIdRouteImport.update({
  id: '/receita/$id',
  path: '/receita/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/despensa': typeof DespensaRoute
  '/dicas': typeof DicasRoute
  '/receita/$id': typeof ReceitaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/despensa': typeof DespensaRoute
  '/dicas': typeof DicasRoute
  '/receita/$id': typeof ReceitaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidade': typeof ComunidadeRoute
  '/despensa': typeof DespensaRoute
  '/dicas': typeof DicasRoute
  '/receita/$id': typeof ReceitaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comunidade' | '/despensa' | '/dicas' | '/receita/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comunidade' | '/despensa' | '/dicas' | '/receita/$id'
  id: '__root__' | '/' | '/comunidade' | '/despensa' | '/dicas' | '/receita/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DespensaRoute: typeof DespensaRoute
  DicasRoute: typeof DicasRoute
  ReceitaIdRoute: typeof ReceitaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despensa': {
      id: '/despensa'
      path: '/despensa'
      fullPath: '/despensa'
      preLoaderRoute: typeof DespensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas': {
      id: '/dicas'
      path: '/dicas'
      fullPath: '/dicas'
      preLoaderRoute: typeof DicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita/$id': {
      id: '/receita/$id'
      path: '/receita/$id'
      fullPath: '/receita/$id'
      preLoaderRoute: typeof ReceitaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadeRoute: ComunidadeRoute,
  DespensaRoute: DespensaRoute,
  DicasRoute: DicasRoute,
  ReceitaIdRoute: ReceitaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
